.gitignore
src/main/java/bookkeeper/Book.java
src/main/java/bookkeeper/BookList.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/Loan.java
src/main/java/bookkeeper/LoanList.java

Split string to obtain loan details for loan object creation.
Closes: #13
Implemented logic to check if loanedBook exists in bookList before adding to loanList.
Closes: #8
Implemented method to list out all existing loans in loanList.
Closes: #10

Add loan object into loanList and view loans in loanList

---

src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java

Update parsing logic for adding new books
Closes #6

Update add-book parsing

---

src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/Loan.java
src/main/java/bookkeeper/LoanList.java

Add delete-loan feature with error catch and JavaDoc
close #9 
Fix bug for addLoan function
close #26

Sheng jie delete loan

---

src/main/java/bookkeeper/BookList.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/LoanList.java

Add remove-book feature with error catch and JavaDoc
Added print message for view-loans when loan list is empty
close #7

Add remove-book function and case for empty loan list

---

src/main/java/bookkeeper/BookList.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/LoanList.java
src/main/java/bookkeeper/exceptions/BookNotFoundException.java
src/main/java/bookkeeper/exceptions/IncorrectFormatException.java

Helps us customize exceptions for our application and improve readability.
- IncorrectFormatException: To be thrown when user Input does not meet expected format.
- BookNotFoundException: To be thrown when a search for a book fails.
Closes #20

Add custom exceptions

---

src/main/java/bookkeeper/InputParser.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Only tested add-loan and view-loans.
Closes #21

Text UI test and Fix extractCommandArgs

---

.gitignore
src/main/java/bookkeeper/BookKeeper.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/LoanList.java
src/main/java/bookkeeper/LoggerConfig.java

Add logging for LoanList (add-loan, delete-loan)

---

src/main/java/bookkeeper/InputParser.java
src/test/java/bookkeeper/InputParserTest.java

Add JUnit tests for InputParser

---

src/main/java/bookkeeper/InputHandler.java

add help command

---

src/main/java/bookkeeper/Book.java
src/main/java/bookkeeper/BookList.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/LoanList.java
text-ui-test/EXPECTED.TXT

Add add-note and delete-note command into help command output

---

src/main/java/bookkeeper/Book.java
src/main/java/bookkeeper/Formatter.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/test/java/bookkeeper/InputParserTest.java

Add command to update book details
Closes #68

Add update-book

---

src/main/java/bookkeeper/Book.java
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/test/java/bookkeeper/BookListTest.java
src/test/java/bookkeeper/InputParserTest.java
src/test/java/bookkeeper/LoanListTest.java
text-ui-test/EXPECTED.TXT

Add location attribute to Book, update addBook, InputParser tests and help message

---

src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/Loan.java
src/test/java/bookkeeper/InputParserTest.java
src/test/java/bookkeeper/LoanListTest.java
text-ui-test/EXPECTED.TXT

Sheng jie edit loans

---

src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/exceptions/ErrorMessages.java
src/test/java/bookkeeper/InputParserTest.java

For easier editing in future if changes are required.
Closes #72

Created ErrorMessages class to store error messages as constants

---

src/main/java/bookkeeper/InputParser.java

Exception not thrown when location not provided

Fix bug extractAddBookArgs 

---

.gitignore
src/main/java/bookkeeper/InputHandler.java
src/main/java/bookkeeper/Loan.java
src/main/java/bookkeeper/Storage.java

Add Storage.java with saveloans method

---

src/main/java/bookkeeper/InputParser.java
src/main/java/bookkeeper/exceptions/ErrorMessages.java
src/test/java/bookkeeper/InputParserTest.java

Add Dynamic Ordering of Arguments and Duplicate Argument Exception Handling

---

docs/UserGuide.md

Updated UG for formatting consistency and added contents page
closes #118

add content page

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/bookkeeper/logic/InputParser.java

Add details to DG for
1. Acknowledgements
2. add-book
3. view-inventory
4. update-book
closes #122 , closes #121

Update developer guide

---

docs/UserGuide.md

Add page breaks for pdf formatting

add page breaks to user guide

---

docs/UserGuide.md

Update page break for formatting

update page break

---

docs/DeveloperGuide.md

Add DG details for `view-loans` and `edit-loan`
closes #129

Update user guide

---

docs/UserGuide.md

Update page breaks for formatting

User guide page break

---

docs/team/dylankhoo.md

Add draft Project Portfolio Page for @dylankhoo

Add draft for dylankhoo PPP

---

docs/UserGuide.md

Add expected outcomes for all commands to user guide

Add expected outcomes

---

docs/DeveloperGuide.md

Fix Inconsistent Book Conditions in DG

---

src/main/java/bookkeeper/logic/InputParser.java

Fix Parser to handle missing parameters

---

src/main/java/bookkeeper/exceptions/ErrorMessages.java
src/main/java/bookkeeper/logic/InputHandler.java
src/main/java/bookkeeper/logic/InputParser.java
text-ui-test/EXPECTED.TXT

added update-note function

---

docs/UserGuide.md
src/main/java/bookkeeper/exceptions/ErrorMessages.java
src/main/java/bookkeeper/logic/InputParser.java

Add validation for phone number and email in edit and add loan

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/classDiagram.puml
src/main/java/bookkeeper/list/BookList.java
src/main/java/bookkeeper/model/Book.java
src/main/java/bookkeeper/model/Category.java
src/main/java/bookkeeper/storage/Storage.java
src/test/java/bookkeeper/BookListTest.java

Using enum helps us validate user input for category.
Closes #69
Closes #198

Change book category from string to enum

---

src/main/java/bookkeeper/model/Book.java

Update `view-inventory` command to reflect "Out on loan" for books that are on loan.
Closes #200

Update view-inventory for books on loan

---

docs/UserGuide.md
src/main/java/bookkeeper/exceptions/ErrorMessages.java
src/main/java/bookkeeper/logic/InputHandler.java
src/main/java/bookkeeper/logic/InputParser.java
src/main/java/bookkeeper/model/Book.java
src/main/java/bookkeeper/model/Loan.java
src/test/java/bookkeeper/InputParserTest.java

Refactor code to allow optional fields for update-book, and provide a way to update titles through new `update-title` command. Remove redundant note commands `add-note`, `update-note`, `delete-note`. Update UG accordingly.
Closes #197 
Closes #173

Refactor update book

---

docs/UserGuide.md

PR to update page break for UG

Update UG page break 1

---

docs/UserGuide.md

Update UG to add constraints and other missing information

Update missing info

---

docs/team/dylankhoo.md

Update PPP for submission page limit

Update dylan-PPP for page limit

---

docs/team/dylankhoo.md

Update PPP for submission page limit

Update dylan-PPP for page length constraints
